### ISSUE TITLE
Cannot invite, waited for almost 30 minutes

### ISSUE THREAD

**Issue by borjita2019** [thelennylord/rblx_rich_presence#1]
The title says it all.

**Comment by thelennylord** [comment]
Did you restart Discord after opening the rich presence program? Sometimes Discord fails to register the app but restarting it seems to fix it.

**Comment by borjita2019** [comment]
this was on 0.1.8

**Comment by borjita2019** [comment]
did it but still cant invite

**Comment by thelennylord** [comment]
> this was on 0.1.8

Could you try reproducing it on 0.1.9?

**Comment by borjita2019** [comment]
Could not generate authentication ticket; Provided .ROBLOSECURITY cookie might be invalid.

**Comment by thelennylord** [comment]
> Could not generate authentication ticket; Provided .ROBLOSECURITY cookie might be invalid.

I've just released a new [build](https://github.com/thelennylord/rblx_rich_presence/releases/tag/v0.1.10) which fixes #2, could you try using the new build? 

Once you're in an experience, it should give you an option to invite users (unless the server you're in is full)

**Comment by borjita2019** [comment]
server is not full but still cant invite

**Comment by borjita2019** [comment]
it shows the presence

**Comment by thelennylord** [comment]
Can't seem to reproduce the issue on my end. Does opening Discord as admin help?

**Comment by borjita2019** [comment]
No.

**Comment by borjita2019** [comment]
![image](https://user-images.githubusercontent.com/63255187/126682186-aff3085c-8e0c-4433-aa31-86164e564565.png)
![image](https://user-images.githubusercontent.com/63255187/126682216-eb7384ab-6fbb-4cd7-aa10-190b6cee3859.png)

**Comment by thelennylord** [comment]
I think I might know whats causing the issue based from the screenshots you've given. Currently, the rich presence program is only able to get the number of players if you're in a public server. It won't work in experiences which have universes or in a private server.

I did sometimes experience where it would fail to get the player count even on public servers, so it could be the issue you're facing right now. I yet have to find a workaround for it.

**Comment by borjita2019** [comment]
Did you find anything?

**Comment by ypurpl** [comment]
![Discord_ezBM0GL43K](https://user-images.githubusercontent.com/81705406/126875440-ba96315d-d585-47f4-bde6-d0a456fa240e.png)
thanks so much, i love it

**Comment by borjita2019** [comment]
how did you get that

**Comment by borjita2019** [comment]
the invite thing i mean

**Comment by borjita2019** [comment]
Well, this is awkward...
Roblox Rich Presence encountered an issue and had to shut down.
To help us diagnose and fix this issue, you may report it along with the below error message at https://github.com/thelennylord/rblx_rich_presence/issues

Error message:
thread 'unknown' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 3, column: 1)', src\roblox.rs:494:82

Press any key to continue...


Well, this is awkward...
Roblox Rich Presence encountered an issue and had to shut down.
To help us diagnose and fix this issue, you may report it along with the below error message at https://github.com/thelennylord/rblx_rich_presence/issues

Error message:
thread 'unknown' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src\utils.rs:27:32

Press any key to continue...

**Comment by borjita2019** [comment]
pressed debug and this happened

**Comment by ypurpl** [comment]
Maybe try downloading new release. Delete config.toml as well

**Comment by borjita2019** [comment]
already got the new release, deleted config.toml and still nothing
