### ISSUE TITLE
A keyring for a token, what?

### ISSUE THREAD

**Issue by borjita2019** [thelennylord/rblx_rich_presence#11]
![image](https://user-images.githubusercontent.com/63255187/231579702-94192b5d-9360-4dc0-a949-d3ff0c80f200.png)
i need the token to be saved on a keyring from what i understand

**Comment by thelennylord** [comment]
The authentication ticket you provided is invalid, so it defaulted to generating a new one from the saved security cookie. In your case, you don't have the security cookie saved in your keyring so it errored. I should make it so it displays the correct error message.
