### ISSUE TITLE
Could not generate authentication ticket; Provided .ROBLOSECURITY cookie might be invalid.

### ISSUE THREAD

**Issue by ypurpl** [thelennylord/rblx_rich_presence#2]
![image](https://user-images.githubusercontent.com/81705406/126160124-5e6f33fd-971b-472f-82f1-1b02061838a5.png)
how to fix this?

**Comment by thelennylord** [comment]
This seems to be a bug due to a recent change in the Roblox API. I'll work on fixing it soon and push out a release.

**Comment by ypurpl** [comment]
Ok, let me know when you're done

**Comment by thelennylord** [comment]
Just released a new [build](https://github.com/thelennylord/rblx_rich_presence/releases/tag/v0.1.10) which fixes this issue.
