### ISSUE TITLE
Unable to join a game

### ISSUE THREAD

**Issue by Camuise** [thelennylord/rblx_rich_presence#5]
When trying to join a game, I get the following error:
![image](https://user-images.githubusercontent.com/46655509/186786901-628e0d87-2edd-48e9-95d9-291750364420.png)

I am able to join games when not running the program.

**Comment by borjita2019** [comment]
this is discontinued.

**Comment by Enock-Thurston** [comment]
Damn. That sucks, hope this gets worked on again, looking forward to a rich presence like this.
