### ISSUE TITLE
Building the build to build the build

### ISSUE THREAD

**Issue by borjita2019** [thelennylord/rblx_rich_presence#6]
yeah ik, confusing title.

can you make some github actions so we can try it out? 

as always, an error from me trying to build this (running linux if that helps)

```
# github.com/thelennylord/discord-rpc/ipc
../go/pkg/mod/github.com/thelennylord/discord-rpc@v0.0.0-20230329170837-d89249406b2d/ipc/ipc_notwin.go:14:14: syntax error: unexpected err at end of statement
```

**Comment by Enock-Thurston** [comment]
Could you send me the ipc_notwin.go file so that I can take a look at it?

**Comment by borjita2019** [comment]
theres no ipc, its a connection to github i think

**Comment by borjita2019** [comment]
wait a minute

**Comment by borjita2019** [comment]
dont tell me

**Comment by Enock-Thurston** [comment]
LOL

**Comment by borjita2019** [comment]
nvm, still doesnt work (used git clone)

**Comment by Enock-Thurston** [comment]
> nvm, still doesnt work (used git clone)

I'm mostly here to try and assist whilst I also learn more about coding. I'm bored af anyways.

**Comment by Enock-Thurston** [comment]
> nvm, still doesnt work (used git clone)

So everytime you use git clone and also attempt to build it you get that error?

**Comment by borjita2019** [comment]
> > nvm, still doesnt work (used git clone)
> 
> So everytime you use git clone and also attempt to build it you get that error?

not like that, i mean when i use "go build" that happens

**Comment by Enock-Thurston** [comment]
Could be related to the go build process itself I assume. But I think the syntax error in the code is what may be causing the build to fail. Although I might be wrong. Or just missing dependencies or no read and execute permissions.

**Comment by Enock-Thurston** [comment]
Could be outdated packages too. Idk though.

**Comment by thelennylord** [comment]
It's a problem with the discord-rpc package I've forked. One of the commits in the original was a rewrite of the package; however seems like ip_notwin.go was left untouched, causing it to break. I'll get on fixing it soon.

**Comment by thelennylord** [comment]
> can you make some github actions so we can try it out?

I'm planning to add those later today.

**Comment by thelennylord** [comment]
Should be fixed now.

**Comment by Enock-Thurston** [comment]
> It's a problem with the discord-rpc package I've forked. One of the commits in the original was a rewrite of the package; however seems like ip_notwin.go was left untouched, causing it to break. I'll get on fixing it soon.

Ah, I sort of figured that was the problem, let me know if there's anything I can do to assist you.
