### ISSUE TITLE
No roblox directory.. but there is?

### ISSUE THREAD

**Issue by borjita2019** [thelennylord/rblx_rich_presence#7]
I have tried the latest rewrite action

![image](https://user-images.githubusercontent.com/63255187/230821550-acbe159f-9585-4505-bc3c-16fc37dd675d.png)

It seems that it cannot find my roblox directory, and by looking at config.go i can confirm my roblox directory is the first one listed
```
	possibleDirs := []string{
		`C:\Users\` + currUser.Name + `\AppData\Local\Roblox\Versions`,
		`C:\Program Files\Roblox\Versions`,
		`C:\Program Files (x86)\Roblox\Versions`,
	}
```

**Comment by thelennylord** [comment]
It's working on my end. What's your Windows username?

**Comment by thelennylord** [comment]
I pushed a new commit which adds more logs when it tries to find Roblox. Could you give that a try and check the logs?

**Comment by borjita2019** [comment]
![image](https://user-images.githubusercontent.com/63255187/230911481-c2d95ae4-8903-4e55-8dab-0d17fbfcbefc.png)
Apparently it doesn't add my windows user to the directory (it's that AppData one)

**Comment by borjita2019** [comment]
> ![image](https://user-images.githubusercontent.com/63255187/230911481-c2d95ae4-8903-4e55-8dab-0d17fbfcbefc.png) Apparently it doesn't add my windows user to the directory (it's that AppData one)

might have been that winteros ive installed that disables some service for it to look at my directory

**Comment by borjita2019** [comment]
what services does windows need to look for the username?

**Comment by thelennylord** [comment]
> what services does windows need to look for the username?
I'm not sure which service Windows uses.

Does `%LocalAppData%` environment variable give you the path to AppData/Local? You can check it in command prompt by executing `echo %localappdata%`

**Comment by borjita2019** [comment]
> > what services does windows need to look for the username?
> > I'm not sure which service Windows uses.
> 
> Does `%LocalAppData%` environment variable give you the path to AppData/Local? You can check it in command prompt by executing `echo %localappdata%`

it seems that it doesn't, btw i changed the code and now it finds the directory but doesn't seem to do anything (it finds it and then closes)

can you send me a screenshot of what its supposed to look like?

**Comment by thelennylord** [comment]
> > > what services does windows need to look for the username?
> > > I'm not sure which service Windows uses.
> > 
> > 
> > Does `%LocalAppData%` environment variable give you the path to AppData/Local? You can check it in command prompt by executing `echo %localappdata%`
> 
> it seems that it doesn't, btw i changed the code and now it finds the directory but doesn't seem to do anything (it finds it and then closes)
> 
> can you send me a screenshot of what its supposed to look like?

What changes did you make, can you send those here?

A screenshot of what?

**Comment by borjita2019** [comment]
> > > > what services does windows need to look for the username?
> > > > I'm not sure which service Windows uses.
> > > 
> > > 
> > > Does `%LocalAppData%` environment variable give you the path to AppData/Local? You can check it in command prompt by executing `echo %localappdata%`
> > 
> > 
> > it seems that it doesn't, btw i changed the code and now it finds the directory but doesn't seem to do anything (it finds it and then closes)
> > can you send me a screenshot of what its supposed to look like?
> 
> What changes did you make, can you send those here?
> 
> A screenshot of what?

i mean, my windows IS winteros (optimized version, and using %localappdata% on run does work and it takes me to local appdata)

a screenshot of what the program shoud look like when you open it (and maybe how the presence looks)

**Comment by thelennylord** [comment]
> i mean, my windows IS winteros (optimized version, and using %localappdata% on run does work and it takes me to local appdata)

Ah got it; I'll make some changes so it uses `%localappdata%` to get the directory instead of relying on the username as that can return empty.


> a screenshot of what the program shoud look like when you open it (and maybe how the presence looks)
Currently, it just closes when you open it; eventually I'll change this behaviour once I have completed implementing the basic features. You can manually launch it by supplying the `roblox-player` URI protocol as the argument. 

...and while getting a screenshot of the presence I encountered a bug lol; I'll fix that in the next commit.

**Comment by thelennylord** [comment]
Should be fixed in the latest commit.

**Comment by borjita2019** [comment]
> Should be fixed in the latest commit.

you just HAD to do it when i got to school

lmao
