### ISSUE TITLE
rblx rich presence? more like rblx

### ISSUE THREAD

**Issue by borjita2019** [thelennylord/rblx_rich_presence#8]
if you understood the joke then you know whats coming

the program literally does not do its thing
![image](https://user-images.githubusercontent.com/63255187/231005329-594ed05f-d27c-4dfa-bedd-8d473d1c18e2.png)
there is no presence changed and it doesnt run on background or anything

(latest rewrite commit)

**Comment by thelennylord** [comment]
I can't reproduce this. The rich presence works on my end. Could you check the logs and send them here?

**Comment by borjita2019** [comment]
[log.txt](https://github.com/thelennylord/rblx_rich_presence/files/11201178/log.txt)

i have discord opened btw

**Comment by thelennylord** [comment]
Could you try the new build? It has more logs added to it which could help in debugging.

**Comment by borjita2019** [comment]
[log.txt](https://github.com/thelennylord/rblx_rich_presence/files/11201425/log.txt)

new build

**Comment by borjita2019** [comment]
nothing changes when i open roblox.

**Comment by thelennylord** [comment]
Ah, you're trying to directly launch it. I haven't implemented that feature yet but planning to in a week or two. For now, you would need to supply the roblox-player protocol as an argument to the program if you just want to test it out.

**Comment by borjita2019** [comment]
> Ah, you're trying to directly launch it. I haven't implemented that feature yet but planning to in a week or two. For now, you would need to supply the roblox-player protocol as an argument to the program if you just want to test it out.

and how would i do that?

**Comment by borjita2019** [comment]
i need to get my token to my keyring appearently
![image](https://user-images.githubusercontent.com/63255187/231308435-b21bcd89-b758-47fd-bc31-b6fd847c2697.png)
HOW DO I DO THAAAAAAAAT

**Comment by thelennylord** [comment]
> i need to get my token to my keyring appearently ![image](https://user-images.githubusercontent.com/63255187/231308435-b21bcd89-b758-47fd-bc31-b6fd847c2697.png) HOW DO I DO THAAAAAAAAT

Seems to be a separate bug. Could you open another issue for that bug?

**Comment by thelennylord** [comment]
Added in latest commit

**Comment by thelennylord** [comment]
Should elaborate more: Launch the program once so it can begin setting up. Once that's done (you can confirm whether setup was successful by viewing the logs), join any Roblox game normally.
